language: php

php:
  - '5.5'
  - '5.6'
  - '7.0'
  - hhvm

install:
  - npm install phantomjs
  - npm install casperjs
  - composer install

notifications:
  on_success: always
  on_failure: always

addons:
  firefox: latest

env:
  - SLIMERJSLAUNCHER=$HOME/firefox-latest/firefox/firefox
